### PR TITLE
Support Managed Interactives

### PR DESCRIPTION
**Pull request by pjanik**
[#173015432]

I was struggling with local test setup, but I ended up copying deployed plugin on S3 and modifying manifest there. It's added to LARA staging as TEST sharing plugin. Here's activity that uses it:
https://authoring.staging.concord.org/activities/20091/pages/307474
(I also added DocStore library interactive first)
I tested everything using Portal and two students and it works fine. You can assign this this interactive to your own class to see it working, but I guess Kevin will be doing some QA anyway.

### CODE REVIEW

**Comment by dougmartin** [comment]
@pjanik it looks like an old version of `request` being required by an older version of `cypress`.  I would try updating `cypress` to the latest 3.x version (3.8.3):

```
"cypress": {
      "version": "3.1.0",
      "resolved": "https://registry.npmjs.org/cypress/-/cypress-3.1.0.tgz",
      "integrity": "sha512-UqLbXgHvM8Y6Y+roHrepZMWcyMN5u4KcjpTbJTZi0d5O2Prvtqmnpoky7a4C65q4oRQXeSc6cBZUhxJkhU4pbQ==",
      "dev": true,
      "requires": {
        "@cypress/listr-verbose-renderer": "0.4.1",
        "@cypress/xvfb": "1.2.3",
        "@types/blob-util": "1.3.3",
        "@types/bluebird": "3.5.18",
        "@types/chai": "4.0.8",
        "@types/chai-jquery": "1.1.35",
        "@types/jquery": "3.2.16",
        "@types/lodash": "4.14.87",
        "@types/minimatch": "3.0.3",
        "@types/mocha": "2.2.44",
        "@types/sinon": "4.0.0",
        "@types/sinon-chai": "2.7.29",
        "bluebird": "3.5.0",
        "cachedir": "1.3.0",
        "chalk": "2.4.1",
        "check-more-types": "2.24.0",
        "commander": "2.11.0",
        "common-tags": "1.4.0",
        "debug": "3.1.0",
        "execa": "0.10.0",
        "executable": "4.1.1",
        "extract-zip": "1.6.6",
        "fs-extra": "4.0.1",
        "getos": "3.1.0",
        "glob": "7.1.2",
        "is-ci": "1.0.10",
        "is-installed-globally": "0.1.0",
        "lazy-ass": "1.6.0",
        "listr": "0.12.0",
        "lodash": "4.17.10",
        "log-symbols": "2.2.0",
        "minimist": "1.2.0",
        "progress": "1.1.8",
        "ramda": "0.24.1",
        "request": "2.87.0",
        "request-progress": "0.3.1",
        "supports-color": "5.1.0",
        "tmp": "0.0.31",
        "url": "0.11.0",
        "yauzl": "2.8.0"
      },
``

**Comment by pjanik** [comment]
Cypress update didn't help in my case, even to 4.7.0. Sass wasn't building, then something with svgr and/or @babel/preset-env. It seems there's a chain of necessary updates.

**Comment by scytacki** [comment]
OK I'll merge this as is, and we'll deal with the build problem later.
I guess this means you'll need to do a manual release of 3.1.3.

**Comment by pjanik** [comment]
@scytacki, I did it. And updated LARA staging to use it:
https://authoring.staging.concord.org/approved_scripts/13/edit

**Pull request merged**
